# Generated by Django 4.2.6 on 2024-01-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='digitalservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digitalservices_icon', models.CharField(max_length=50)),
                ('digitalservices_title', models.CharField(max_length=50)),
                ('digitalservices', models.TextField()),
            ],
        ),
    ]
