# Generated by Django 4.2.6 on 2024-01-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketingservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalservices',
            old_name='digitalservices',
            new_name='digitalservices_dec',
        ),
    ]
