# Generated by Django 4.2.6 on 2024-02-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketingservices', '0003_alter_digitalservices_digitalservices_dec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalservices',
            name='digitalservices_dec',
            field=models.TextField(),
        ),
    ]
