# Generated by Django 4.2.6 on 2024-01-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graphicservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphicservices_icon', models.CharField(max_length=50)),
                ('graphicservices_title', models.CharField(max_length=50)),
                ('graphicservices_dec', models.TextField()),
            ],
        ),
    ]
